[build]
  functions = "functions"
  # This will be run the site build
  command = "npm run build"
  # This is the directory is publishing to netlify's CDN
  publish = "dist"

[dev]
  # Local dev command. A.k.a npm start 
  publish = "dist"